package extrabiomes.api;

import java.util.HashMap;
import java.util.Map;

/**
 * Enum of blocks used in terrain generation
 * 
 * @author ScottKillen
 *
 */
public enum TerrainGenBlock {
	CRACKED_SAND,
	RED_ROCK,
	QUICKSAND,
	BROWN_LEAVES,
	ORANGE_LEAVES,
	PURPLE_LEAVES,
	YELLOW_LEAVES,
	FIR_LEAVES,
	REDWOOD_LEAVES,
	ACACIA_LEAVES,
	AUTUMN_SHRUB,
	HYDRANGEA,
	ORANGE_FLOWER,
	PURPLE_FLOWER,
	TINY_CACTUS,
	ROOT,
	TOAD_STOOL,
	WHITE_FLOWER,
	BROWN_GRASS,
	SHORT_BROWN_GRASS,
	DEAD_GRASS,
	DEAD_TALL_GRASS,
	YELLOW_DEAD_GRASS,
	BROWN_SAPLING,
	ORANGE_SAPLING,
	PURPLE_SAPLING,
	YELLOW_SAPLING,
	FIR_SAPLING,
	REDWOOD_SAPLING,
	ACACIA_SAPLING,
	CAT_TAIL,
	LEAF_PILE,
	AUTUMN_WOOD,
	FIR_WOOD,
	REDWOOD_WOOD,
	ACACIA_WOOD;
}
