
package org.bukkit.block;

public enum Biome {
	RAINFOREST, SWAMPLAND, SEASONAL_FOREST, FOREST, SAVANNA, SHRUBLAND,
	TAIGA, DESERT, PLAINS, ICE_DESERT, TUNDRA, HELL, SKY, OCEAN, RIVER,
	EXTREME_HILLS, FROZEN_OCEAN, FROZEN_RIVER, ICE_PLAINS, ICE_MOUNTAINS,
	MUSHROOM_ISLAND, MUSHROOM_SHORE, BEACH, DESERT_HILLS, FOREST_HILLS,
	TAIGA_HILLS, SMALL_MOUNTAINS, JUNGLE, JUNGLE_HILLS, ALPINE,
	AUTUMN_WOODS, BIRCH_FOREST, EXTREME_JUNGLE, FORESTED_HILLS,
	FORESTED_ISLAND, GLACIER, GREEN_HILLS, GREEN_SWAMP, ICE_WASTELAND, MARSH,
	MEADOW, MINI_JUNGLE, MOUNTAIN_DESERT, MOUNTAIN_RIDGE, MOUNTAIN_TAIGA,
	SNOW_FOREST, PINE_FOREST, REDWOOD_FOREST, REDWOOD_LUSH, SNOWY_RAINFOREST,
	TEMPORATE_RAINFOREST, WASTELAND, WOODLANDS;
}
